# 7. Dataframes

Dataframes are used extensively in the analysis of real world data. In this lab, we will use dataframes to review the basic Python skills we have introduced in this chapter:

<ul>
    <li> 1. (user-defined) functions </li>
    <li> 2.the numpy library</li>
    <li> 3. the pandas library  </li>
    <li> 4. the matplotlib library </li>
    <li> 5. for loops  </li>
    <li> 6. if conditionals </li>
    </ul>
    
In particular, we will use a dataframe called COVID to explore COVID-19 data imported directly from the City of Chicago's Data Portal.  

1) Let's start by importing the  numpy and pandas libraries. In general, we will always begin by importing these two libraries.

In [1]:
import numpy as np
import pandas as pd

2) We can use pandas (pd) to get up-to-date info about COVID 19. Let's create a dataframe called rawCOVID containing data either by reading the excel file "rawCOCID.xlsx" (data as of June 27, 2023) or by importing the data directly from the Chicago Data Portal and then display the first line of this dataframe.

In [2]:
rawCOVID=pd.read_excel("rawCOVID.xlsx")
# rawCOVID=pd.read_json("https://data.cityofchicago.org/resource/yhhz-zm2v.json?$limit=5000000")
rawCOVID.head(1)

Unnamed: 0  :@computed_region_43wa_7qmu  :@computed_region_6mkv_f3dw   
0           0                         36.0                      14309.0  \

   :@computed_region_bdys_3d7i  :@computed_region_rpca_8um6   
0                        580.0                         42.0  \

   :@computed_region_vrxf_vc4k  case_rate_cumulative  case_rate_weekly   
0                         38.0                 654.2              27.3  \

   cases_cumulative  cases_weekly  ...         row_id  test_rate_cumulative   
0              96.0           4.0  ...  60601-2020-28                9799.0  \

   test_rate_weekly  tests_cumulative  tests_weekly                 week_end   
0            1376.5              1438         202.0  2020-07-11T00:00:00.000  \

   week_number               week_start  zip_code   
0           28  2020-07-05T00:00:00.000     60601  \

                                   zip_code_location  
0  {'type': 'Point', 'coordinates': [-87.622844, ...  

[1 rows x 27 columns]

3) Let's list just the columns in the rawCOVID dataframe.

In [3]:
rawCOVID.columns

Index(['Unnamed: 0', ':@computed_region_43wa_7qmu',
       ':@computed_region_6mkv_f3dw', ':@computed_region_bdys_3d7i',
       ':@computed_region_rpca_8um6', ':@computed_region_vrxf_vc4k',
       'case_rate_cumulative', 'case_rate_weekly', 'cases_cumulative',
       'cases_weekly', 'death_rate_cumulative', 'death_rate_weekly',
       'deaths_cumulative', 'deaths_weekly',
       'percent_tested_positive_cumulative', 'percent_tested_positive_weekly',
       'population', 'row_id', 'test_rate_cumulative', 'test_rate_weekly',
       'tests_cumulative', 'tests_weekly', 'week_end', 'week_number',
       'week_start', 'zip_code', 'zip_code_location'],
      dtype='object')

4) Let's get the number of rows and columns in our dataframe.

In [4]:
rawCOVID.shape

(10320, 27)

5) Let's define a dataframe COVID which uses just 4 columns from rawCOVID: deaths_cumulative, population, tests_cumulative, and zip_code.

In [5]:
COVID=rawCOVID[["deaths_cumulative", "population", "tests_cumulative","zip_code"]]
COVID.head(1)

deaths_cumulative  population  tests_cumulative zip_code
0                  5       14675              1438    60601

6) Let's shorten the column names.

In [6]:
COVID.columns=["deaths","population","tests","zip"]
COVID.head(15)

deaths  population  tests    zip
0        5       14675   1438  60601
1        0        1174   6680  60603
2        0        1174   6963  60603
3        0        1174   7218  60603
4        0        1174   7560  60603
5        0        1174   7942  60603
6        0         782  10250  60604
7        0         782  10457  60604
8        0         782  10718  60604
9        0         782  12597  60604
10       0         782  12718  60604
11       0         782  12814  60604
12       0         782  12911  60604
13       0         782  13000  60604
14       0         782  13083  60604

7) We can get the latest test info for zip 60604  by first creating a datframe df for that zip code, and then using max() to get the highest value in the "tests" column.

In [7]:
df = COVID[COVID["zip"]=='60604']
numtested=df["tests"].max()
numtested

15747

8) Let's define a function MyCOVID(COVID,zip) which allows us to enter a 5-digit zip code number and have the computer tell us how many tests, and the number of deaths.

In [8]:
def MyCOVID(COVID,zipcode):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zipcode and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only process data for each zipcode once
            df=COVID[COVID["zip"]==zipcode]
            numtested=df["tests"].max()
            numdeaths=df["deaths"].max()
            print("Zip code: ", COVID.loc[z,"zip"])
            print("number tested is ", numtested)
            print("number deaths ", numdeaths)
    return ("Enter a different zip code if you wish.")

9) Let's see if there's data for zipcode='60623'.

In [9]:
zipcode='60623'
MyCOVID(COVID,zipcode)

Zip code:  60623
number tested is  435801
number deaths  334


'Enter a different zip code if you wish.'

10) Now analyze zipicode='60637'

In [10]:
zipcode='60637'
MyCOVID(COVID,zipcode)

Zip code:  60637
number tested is  413295
number deaths  106


'Enter a different zip code if you wish.'

<h4>Assignment</h4>
Modify the MyCOVID function so that a function MyCOVID2 also includes the population of the input zipcode. Then check that your function works on zipcode='60637'

In [11]:
# Define MyCOVID2


In [12]:
# Check that the function is working

<h4>Solution</h4>

In [13]:
#Define MyCOVID2
def MyCOVID2(COVID,zipcode):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zipcode and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only do this once
            df=COVID[COVID["zip"]==zipcode]
            population=df["population"].max()
            numtested=df["tests"].max()
            numdeaths=df["deaths"].max()
            print("Zip code: ", COVID.loc[z,"zip"])
            print("population is ", population)
            print("number tested is ", numtested)
            print("number deaths ", numdeaths)
    return ("Enter a different zip code if you wish.")

In [14]:
# Check that the function is working
MyCOVID2(COVID,'60637')

Zip code:  60637
population is  47454
number tested is  413295
number deaths  106


'Enter a different zip code if you wish.'