# 2 How bad is COVID by Chicago Zipcode

In this lab we will analyze data imported directly from the Chicago Data Portal

https://data.cityofchicago.org/

<h3> STEP 1</h3>
Let's read in up to 100,000 rows of COVID data for Chicago from the Chicago Data Portal.

In [1]:
import pandas as pd
import numpy as np
rawCOVID = pd.read_json('https://data.cityofchicago.org/resource/yhhz-zm2v.json?$limit=100000') #Import data directly from data portal
rawCOVID.head(10)

:@computed_region_43wa_7qmu  :@computed_region_6mkv_f3dw  \
0                         36.0                      14311.0   
1                         36.0                      14311.0   
2                         36.0                      14311.0   
3                         36.0                      14311.0   
4                         36.0                      14311.0   
5                         36.0                      14311.0   
6                         36.0                      14311.0   
7                         36.0                      14311.0   
8                         36.0                      14311.0   
9                         36.0                      14311.0   

   :@computed_region_bdys_3d7i  :@computed_region_rpca_8um6  \
0                        367.0                         34.0   
1                        367.0                         34.0   
2                        367.0                         34.0   
3                        367.0                         34.0   
4                        367.0                         34.0   
5                        367.0                         34.0   
6                        367.0                         34.0   
7                        367.0                         34.0   
8                        367.0                         34.0   
9                        367.0                         34.0   

   :@computed_region_vrxf_vc4k  case_rate_cumulative  case_rate_weekly  \
0                         38.0                   NaN               NaN   
1                         38.0                   NaN               NaN   
2                         38.0                   NaN               NaN   
3                         38.0                   NaN               NaN   
4                         38.0                   NaN               NaN   
5                         38.0                   NaN               NaN   
6                         38.0                   NaN               NaN   
7                         38.0                   NaN               NaN   
8                         38.0                   NaN               NaN   
9                         38.0                   NaN               NaN   

   cases_cumulative  cases_weekly  death_rate_cumulative  \
0               NaN           NaN                    0.0   
1               NaN           NaN                    0.0   
2               NaN           NaN                    0.0   
3               NaN           NaN                    0.0   
4               NaN           NaN                    0.0   
5               NaN           NaN                    0.0   
6               NaN           NaN                    0.0   
7               NaN           NaN                    0.0   
8               NaN           NaN                    0.0   
9               NaN           NaN                    0.0   

                         ...                                 row_id  \
0                        ...                          60603-2020-10   
1                        ...                          60603-2020-11   
2                        ...                          60603-2020-12   
3                        ...                          60603-2020-13   
4                        ...                          60603-2020-14   
5                        ...                          60603-2020-15   
6                        ...                          60603-2020-16   
7                        ...                          60603-2020-17   
8                        ...                          60603-2020-18   
9                        ...                          60603-2020-19   

   test_rate_cumulative  test_rate_weekly  tests_cumulative  tests_weekly  \
0                   0.0               0.0                 0           0.0   
1                   0.0               0.0                 0           0.0   
2                  85.2              85.2                 1           1.0   
3                 340.7             255.5        

We'll list the 26 column names

In [3]:
rawCOVID.shape

(8280, 26)

In [2]:
list(rawCOVID.columns)

[':@computed_region_43wa_7qmu',
 ':@computed_region_6mkv_f3dw',
 ':@computed_region_bdys_3d7i',
 ':@computed_region_rpca_8um6',
 ':@computed_region_vrxf_vc4k',
 'case_rate_cumulative',
 'case_rate_weekly',
 'cases_cumulative',
 'cases_weekly',
 'death_rate_cumulative',
 'death_rate_weekly',
 'deaths_cumulative',
 'deaths_weekly',
 'percent_tested_positive_cumulative',
 'percent_tested_positive_weekly',
 'population',
 'row_id',
 'test_rate_cumulative',
 'test_rate_weekly',
 'tests_cumulative',
 'tests_weekly',
 'week_end',
 'week_number',
 'week_start',
 'zip_code',
 'zip_code_location']

Q1. .Does case matter when referring to a column name?
<hr>
<h3> STEP TWO </h3>
Let's streamline the data to just 4 columns, drop rows with missing data,  simplify the column names, and then display the first 20 rows.

In [6]:
COVID=rawCOVID[['deaths_cumulative', "population",  'tests_cumulative','zip_code']]
COVID.dropna  #drop rows with missing data
COVID.columns=["deaths","population","tests","zip"] #simplify the column names
COVID.head(20)

deaths  population  tests    zip
0        0        1174      0  60603
1        0        1174      0  60603
2        0        1174      1  60603
3        0        1174      4  60603
4        0        1174     10  60603
5        0        1174     16  60603
6        0        1174     19  60603
7        0        1174     22  60603
8        0        1174     35  60603
9        0        1174     42  60603
10       0        1174     50  60603
11       0        1174     64  60603
12       0        1174     71  60603
13       0        1174     90  60603
14       0        1174    100  60603
15       0        1174    114  60603
16       0        1174    124  60603
17       0        1174    148  60603
18       0        1174    168  60603
19       0        1174    199  60603

Q2. Why is there different information for the same zip code?
<hr>
<h3> STEP THREE</h3>
Let's check how many rows have data in each column</h3>

In [7]:
COVID.count()

deaths        8280
population    8280
tests         8280
zip           8280
dtype: int64

Q3.  How many data rows are there in each column?
<hr>
<h3> STEP FOUR</h3>
Let's find out how many times each zip code appears.

In [8]:
COVID["zip"].value_counts()

60634      138
60630      138
60666      138
60610      138
60827      138
60657      138
60622      138
60625      138
60633      138
60606      138
60607      138
60632      138
60659      138
60661      138
60612      138
60642      138
60636      138
60616      138
60629      138
60637      138
60605      138
Unknown    138
60646      138
60618      138
60620      138
60647      138
60608      138
60643      138
60617      138
60602      138
60640      138
60660      138
60639      138
60649      138
60707      138
60611      138
60655      138
60619      138
60651      138
60613      138
60654      138
60615      138
60624      138
60652      138
60621      138
60609      138
60645      138
60614      138
60628      138
60638      138
60601      138
60603      138
60626      138
60641      138
60631      138
60656      138
60623      138
60604      138
60653      138
60644      138
Name: zip, dtype: int64

<h2>STEP FIVE </h2>
Let's make a copy of the COVID dataframe and display the first 5 rows.

In [9]:
df1=COVID
df1.head(5)

deaths  population  tests    zip
0       0        1174      0  60603
1       0        1174      0  60603
2       0        1174      1  60603
3       0        1174      4  60603
4       0        1174     10  60603

<h2> STEP SIX </h2> 

Filter data by a specific zip code, for example, '60611'

In [10]:
df2=df1[df1['zip']=='60611']
df2.head()

deaths  population  tests    zip
952       2       32426   2076  60611
953       2       32426   2476  60611
954       2       32426   2842  60611
955       2       32426   3354  60611
956       3       32426   3827  60611

In [11]:
df2["zip"].value_counts()

60611    138
Name: zip, dtype: int64

<h2> STEP SEVEN </h2>
Let's find the largest value in the 'tests' column for zip '60611'.

In [13]:
df2 = df1[df1["zip"]=='60637'] #get just rows with zip 60611
numtested=df2["tests"].max() #get the largest number for tests
numtested

366842

Question:  How can we find how many deaths due to COVID have occurred in zip '60623'?  (Create a new dataframe for 60623 called temp)

In [15]:
df3 = COVID[df1["zip"]=='60623'] #get just rows with zip 60611
numdeaths=df3["deaths"].max() #get the largest number for tests
numdeaths

330

Question: How can we get the population in 60623?

In [16]:
df3 = COVID[df1["zip"]=='60623'] #get just rows with zip 60611
pop=df3["population"].max() #get the largest number for tests
pop


85979

<h3> STEP EIGHT</h3>
We can instruct the computer to give us the number COVID tests for any Chicago zipcode. </h3>

In [17]:
def MyCOVID(COVID,zip):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zip and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only do this once
            df=COVID[COVID["zip"]==zip]
            numtested=df["tests"].max()
            print("Zip code: ", zip)  #print zipcode
            print("number tested is ", numtested) #print number tested
    return ("Enter a different zip code if you wish.")

Q5. Test out the function on zip code '60610'

In [19]:
MyCOVID(COVID,'60637')

Zip code:  60637
number tested is  366842


'Enter a different zip code if you wish.'

In [ ]:
def MyCOVID2(COVID,zip):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zip and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only do this once
            df=COVID[COVID["zip"]==zip]
            numtested=df["tests"].max()
            numdeaths=df["deaths"].max()
            print("Zip code: ", zip)  #print zipcode
            print("number tested is ", numtested) #print number tested
            print("number of deaths is ", numdeaths) #print number tested
    return ("Enter a different zip code if you wish.")

<h3> Assignment </h3>

In [ ]:
MyCOVID2(COVID,"60619")

Q1)  Define a function myCOVID2() which outputs for each given zip code the population, number tested, and number of deaths. 

Q2)  Use your function myCOVID2() to determine the COVID data for each of the following Chicago landmarks:

a) North Park University (zip  '60625')


In [ ]:
# solution to 2a)

b) Wheaton in Chicago (zip='60637')

In [ ]:
# solution to 2b)

Q3) Why is COVID disproportionately impacting black and brown communities?

### Solutions

Q1)

In [ ]:
def MyCOVID2(COVID,zip):
    alreadychecked=0  #eliminate duplication of information
    for z in COVID.index:  #go through all the index values
        if COVID.loc[z,"zip"]==zip and alreadychecked==0:    #found the zip we requested (first-time)
            alreadychecked=1  #we will only do this once
            df=COVID[COVID["zip"]==zip]
            numtested=df["tests"].max()
            numdeaths=df["deaths"].max()
            print("Zip code: ", zip)  #print zipcode
            print("number tested is ", numtested) #print number tested
            print("number of deaths is ", numdeaths) #print number tested
    return ("Enter a different zip code if you wish.")

Q2a)

In [ ]:
MyCOVID(COVID,'60625')

Q2b)

In [ ]:
MyCOVID(COVID,'60637')

Q3)