title: An Introduction to Python Jupyter Notebooks for College Math Teachers
author: Paul Isihara, Claire Wagner, Peter Jantsch, and Thomas VanDrunen, Editors
copyright: "2024"
logo: logo.png

# Prevent re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: JNBbook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
# (see also myst_substitutions below)
repository:
  url: https://github.com/timothyprojectGiG/JB_Math_Textbook  # Online location of your book
  path_to_book: src  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "classic"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  # For license information
  extra_footer: |
    <p>
      <a rel='license' href='http://creativecommons.org/licenses/by/4.0/'><img alt='Creative Commons License' width=88 style='border-width:0' src='https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by.png'/></a>
      Except where otherwise noted, this work is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a>.
    </p>

parse:
  myst_enable_extensions:
    - html_image
    - amsmath
    - dollarmath
    - smartquotes
    - linkify
    - colon_fence
    - substitution
  myst_substitutions:
    # link to web version of textbook
    web_ver_url: "https://timothyprojectgig.github.io/JB_Math_Textbook"
    repo_url: "https://github.com/timothyprojectGiG/JB_Math_Textbook/tree/main/src"
    binder_url: "https://mybinder.org/v2/gh/timothyprojectGiG/JB_Math_Textbook/main?urlpath=tree/src"

sphinx:
  config:
    latex_additional_files:
      - "custom.tex.txt"
    latex_elements:
      extrapackages: \usepackage{pdfpages}
      preamble: \setcounter{secnumdepth}{2}
      maketitle: | # to correct overflow
        \includepdf[pages=-]{cover.pdf}
        \author{Paul Isihara, Claire Wagner, Peter Jantsch, \and and Thomas VanDrunen, Editors}
        \sphinxmaketitle
      fncychap: \usepackage[Sonny]{fncychap} # for chapter title styling
      extraclassoptions: "openany,oneside" # to avoid unnecessary blank pages
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
