
title: An Introduction to Python Jupyter Notebooks for College Math Teachers
author: Paul Isihara, Peter Jantsch, Thomas VanDrunen, and  Claire Wagner, Editors
copyright: "2023"
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 7200
  exclude_patterns: ['Elementary/Arithmetic/*','Undergrad/Calculus/*','Undergrad/Linear/*','Advanced/AdvDataAnalysis/*','Advanced/Complex/*','Advanced/LinearAlgebra/*','Advanced/LinearAlgebra/*/*','PreCollege/Celestial/*','ProbStat/ProbIntro/drivethru.ipynb','PatternsSOLUTION.ipynb','PreCollege/*/*','ProbStat/StatInf/*','Undergrad/AppliedCalc/*','Undergrad/AppliedDifEq/*','Undergrad/AppliedDifEq/*/*']

only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: JNBbook.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/timothyprojectGiG/JB_Math_Textbook  # Online location of your book
  path_to_book: src  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - html_image
    - amsmath
    - dollarmath
    - smartquotes
    - linkify
    - colon_fence

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
